[project]
name = "michaela-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "openai>=1.55.0",
    "pandas>=2.2.3",
]
